package battleengine

import (
	"fmt"
	"reflect"
	"testing"
)

func itemEvidenceEngine(t *testing.T, enabled bool) *Engine {
	config := testConfig()
	config.Rules.RecordItemEffects = enabled
	config.Rules.SpeedPixelsPerSecondByRate = nativeSpeedPixelsPerSecondByRate
	return mustEngine(t, config)
}

func TestItemAuditIsOptionalAndDoesNotChangeNativePickups(t *testing.T) {
	// All ordinary supported SceneIDs, not shop IDs or just the items most
	// often generated by a particular map's wall table.
	ids := []uint32{1, 2, 3, 4, 5, 6, 7, 8, 21, 23, 24, 25, 26, 27, 28, 47, 61, 62, 81, 82, 83, 84, 85, 93, 94, 101, 104, 107, 108, 109, 110, 114, 115}
	for _, id := range ids {
		t.Run(fmt.Sprint(id), func(t *testing.T) {
			plain, audited := itemEvidenceEngine(t, false), itemEvidenceEngine(t, true)
			pickup := Pickup{SceneID: id, State: PickupAvailable, Cell: Cell{Row: 1, Col: 1}}
			other := pickup
			a := plain.collectPickup(&plain.actors[0], &pickup)
			b := audited.collectPickup(&audited.actors[0], &other)
			if a.ItemChange != nil || b.ItemChange == nil {
				t.Fatal("audit switch not respected")
			}
			if b.ItemChange.After != audited.itemState(&audited.actors[0]) {
				t.Fatal("after state not native")
			}
			b.ItemChange = nil
			if a != b || pickup != other || !reflect.DeepEqual(plain.actors, audited.actors) {
				t.Fatal("audit changed physics")
			}
		})
	}
}

func TestTransformationEvidenceSeparatesLifeRefreshReplacementAndExpiry(t *testing.T) {
	for _, id := range []uint32{101, 104, 107, 108, 109, 110, 114, 115} {
		engine := itemEvidenceEngine(t, true)
		actor := &engine.actors[0]
		pickup := Pickup{SceneID: id, State: PickupAvailable}
		first := engine.collectPickup(actor, &pickup)
		if first.ItemChange.Before.TransformationSceneID != 0 || first.ItemChange.After.TransformationSceneID != id {
			t.Fatal("new form missing")
		}
		engine.elapsedMS += 5000
		refresh := engine.collectPickup(actor, &pickup)
		if refresh.ItemChange.Before.TransformationRemainingMS != 25000 || refresh.ItemChange.After.TransformationRemainingMS != 30000 {
			t.Fatal("refresh treated as independent life")
		}
		// Real impact path: it breaks the form rather than trapping the actor.
		engine.flames = []Flame{{Cell: actor.Position.Cell(), ImpactAtMS: engine.elapsedMS, OwnerID: 2}}
		events := engine.applyFlameHazards()
		if len(events) != 1 || events[0].Kind != EventActorTransformationEnded || actor.State != ActorActive {
			t.Fatalf("form %d did not absorb hit", id)
		}
		change := events[0].ItemChange
		if change.After.TransformationSceneID != 0 || change.After.ProtectionRemainingMS != 3000 {
			t.Fatal("recovery protection missing")
		}
		engine.collectPickup(actor, &pickup)
		if actor.HarmProtectionExpiresAt != 0 {
			t.Fatal("new form incorrectly inherited protection")
		}
	}
	engine := itemEvidenceEngine(t, true)
	actor := &engine.actors[0]
	axe := Pickup{SceneID: 115}
	engine.collectPickup(actor, &axe)
	duck := Pickup{SceneID: 104}
	changed := engine.collectPickup(actor, &duck).ItemChange
	if changed.Before.HeldActions == changed.After.HeldActions || changed.After.CanCollectItems {
		t.Fatal("axe replacement/duck collection restriction lost")
	}
	expired := engine.endTransformation(actor, TransformationEndExpired, 0)
	if expired.TransformationEnd == TransformationEndHit {
		t.Fatal("expiry counted as absorbed attack")
	}
}

func TestInventoryPreviewMatchesMutationIncludingFullInventory(t *testing.T) {
	for _, before := range []uint8{0, 1, 254, 255} {
		actor := Actor{}
		if before > 0 {
			actor.HeldActions[0] = HeldActionSlot{ActionID: 43, Count: before}
		}
		gain := HeldActionGrantAmount(actor.HeldActions, 43, 3)
		grantHeldAction(&actor, 43, 3)
		if int(actorHeldActionCount(&actor, 43))-int(before) != int(gain) {
			t.Fatal("preview differs from native grant")
		}
	}
	actor := Actor{}
	for i := range actor.HeldActions {
		actor.HeldActions[i] = HeldActionSlot{ActionID: uint8(90 + i), Count: 1}
	}
	if HeldActionGrantAmount(actor.HeldActions, 43, 3) != 0 || grantHeldAction(&actor, 43, 3) {
		t.Fatal("full inventory granted new slot")
	}
}

func TestEffectiveMovementObservationUsesNativeOverrideAndKeepsOtherTimersPrivate(t *testing.T) {
	engine := itemEvidenceEngine(t, true)
	actor := &engine.actors[0]
	crab := Pickup{SceneID: 114}
	engine.collectPickup(actor, &crab)
	obs, err := engine.Observation(actor.PlayerID)
	if err != nil {
		t.Fatal(err)
	}
	if obs.Actors[0].HorizontalSpeedPixelsPerSecond != 180 || obs.Actors[0].VerticalSpeedPixelsPerSecond != 72 {
		t.Fatal("crab axes flattened")
	}
	engine.installMovementStatus(actor, MovementStatusForcedSlide)
	obs, _ = engine.Observation(actor.PlayerID)
	if obs.Actors[0].HorizontalSpeedPixelsPerSecond != 520 || obs.Actors[0].VerticalSpeedPixelsPerSecond != 520 {
		t.Fatal("status priority missing")
	}
	other, _ := engine.Observation(engine.actors[1].PlayerID)
	if other.Actors[0].MovementStatusExpiresAt != 0 || other.Actors[0].HorizontalSpeedPixelsPerSecond != 0 {
		t.Fatal("private local fields leaked")
	}
}
